/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ItemName = string;
export type CustomerName = string;
export type Category = string;
export type Time = bigint;
export type SupplierName = string;
export type Description = string;
export interface Purchase {
    supplierName?: SupplierName;
    date: Time;
    totalCost: number;
    itemName: ItemName;
    quantity: bigint;
    unitCost: number;
}
export interface DailyRecord {
    date: Time;
    description: Description;
    category: Category;
    amount: number;
}
export interface SupplierLoan {
    repaid: boolean;
    supplierName: SupplierName;
    date: Time;
    amount: number;
    purpose: string;
}
export interface AdvancePayment {
    settled: boolean;
    supplierName: SupplierName;
    date: Time;
    amount: number;
    purpose: string;
}
export interface UserProfile {
    name: string;
}
export interface Transaction {
    customerName?: CustomerName;
    date: Time;
    totalAmount: number;
    itemName: ItemName;
    quantity: bigint;
    unitPrice: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdvancePayment(amount: number, supplierName: SupplierName, purpose: string): Promise<void>;
    addExpenseRecord(amount: number, category: Category, description: Description): Promise<void>;
    addIncomeRecord(amount: number, category: Category, description: Description): Promise<void>;
    addPurchaseRecord(itemName: ItemName, quantity: bigint, unitCost: number, supplierName: SupplierName | null): Promise<void>;
    addSalesTransaction(itemName: ItemName, quantity: bigint, unitPrice: number, customerName: CustomerName | null): Promise<void>;
    addSupplierLoan(amount: number, supplierName: SupplierName, purpose: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteDailyRecord(): Promise<void>;
    deletePurchaseRecord(): Promise<void>;
    deleteTransaction(): Promise<void>;
    getAdvancePayments(): Promise<Array<AdvancePayment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyRecords(recordType: string): Promise<Array<DailyRecord>>;
    getPurchaseRecords(): Promise<Array<Purchase>>;
    getSalesTransactions(): Promise<Array<Transaction>>;
    getSupplierLoans(): Promise<Array<SupplierLoan>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    repaySupplierLoan(loanIndex: bigint): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    settleAdvancePayment(paymentIndex: bigint): Promise<boolean>;
}
import type { CustomerName as _CustomerName, ItemName as _ItemName, Purchase as _Purchase, SupplierName as _SupplierName, Time as _Time, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdvancePayment(arg0: number, arg1: SupplierName, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdvancePayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdvancePayment(arg0, arg1, arg2);
            return result;
        }
    }
    async addExpenseRecord(arg0: number, arg1: Category, arg2: Description): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpenseRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpenseRecord(arg0, arg1, arg2);
            return result;
        }
    }
    async addIncomeRecord(arg0: number, arg1: Category, arg2: Description): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIncomeRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIncomeRecord(arg0, arg1, arg2);
            return result;
        }
    }
    async addPurchaseRecord(arg0: ItemName, arg1: bigint, arg2: number, arg3: SupplierName | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPurchaseRecord(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPurchaseRecord(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addSalesTransaction(arg0: ItemName, arg1: bigint, arg2: number, arg3: CustomerName | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalesTransaction(arg0, arg1, arg2, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalesTransaction(arg0, arg1, arg2, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addSupplierLoan(arg0: number, arg1: SupplierName, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSupplierLoan(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSupplierLoan(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteDailyRecord(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDailyRecord();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDailyRecord();
            return result;
        }
    }
    async deletePurchaseRecord(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePurchaseRecord();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePurchaseRecord();
            return result;
        }
    }
    async deleteTransaction(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction();
            return result;
        }
    }
    async getAdvancePayments(): Promise<Array<AdvancePayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvancePayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvancePayments();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyRecords(arg0: string): Promise<Array<DailyRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyRecords(arg0);
            return result;
        }
    }
    async getPurchaseRecords(): Promise<Array<Purchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseRecords();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseRecords();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesTransactions();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesTransactions();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupplierLoans(): Promise<Array<SupplierLoan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplierLoans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplierLoans();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async repaySupplierLoan(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.repaySupplierLoan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.repaySupplierLoan(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async settleAdvancePayment(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.settleAdvancePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.settleAdvancePayment(arg0);
            return result;
        }
    }
}
function from_candid_Purchase_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Purchase): Purchase {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupplierName]): SupplierName | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerName]): CustomerName | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    supplierName: [] | [_SupplierName];
    date: _Time;
    totalCost: number;
    itemName: _ItemName;
    quantity: bigint;
    unitCost: number;
}): {
    supplierName?: SupplierName;
    date: Time;
    totalCost: number;
    itemName: ItemName;
    quantity: bigint;
    unitCost: number;
} {
    return {
        supplierName: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.supplierName)),
        date: value.date,
        totalCost: value.totalCost,
        itemName: value.itemName,
        quantity: value.quantity,
        unitCost: value.unitCost
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: [] | [_CustomerName];
    date: _Time;
    totalAmount: number;
    itemName: _ItemName;
    quantity: bigint;
    unitPrice: number;
}): {
    customerName?: CustomerName;
    date: Time;
    totalAmount: number;
    itemName: ItemName;
    quantity: bigint;
    unitPrice: number;
} {
    return {
        customerName: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.customerName)),
        date: value.date,
        totalAmount: value.totalAmount,
        itemName: value.itemName,
        quantity: value.quantity,
        unitPrice: value.unitPrice
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Purchase>): Array<Purchase> {
    return value.map((x)=>from_candid_Purchase_n9(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupplierName | null): [] | [_SupplierName] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerName | null): [] | [_CustomerName] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
