/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SupplierName = IDL.Text;
export const Category = IDL.Text;
export const Description = IDL.Text;
export const ItemName = IDL.Text;
export const CustomerName = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AdvancePayment = IDL.Record({
  'settled' : IDL.Bool,
  'supplierName' : SupplierName,
  'date' : Time,
  'amount' : IDL.Float64,
  'purpose' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DailyRecord = IDL.Record({
  'date' : Time,
  'description' : Description,
  'category' : Category,
  'amount' : IDL.Float64,
});
export const Purchase = IDL.Record({
  'supplierName' : IDL.Opt(SupplierName),
  'date' : Time,
  'totalCost' : IDL.Float64,
  'itemName' : ItemName,
  'quantity' : IDL.Nat,
  'unitCost' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'customerName' : IDL.Opt(CustomerName),
  'date' : Time,
  'totalAmount' : IDL.Float64,
  'itemName' : ItemName,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
});
export const SupplierLoan = IDL.Record({
  'repaid' : IDL.Bool,
  'supplierName' : SupplierName,
  'date' : Time,
  'amount' : IDL.Float64,
  'purpose' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdvancePayment' : IDL.Func([IDL.Float64, SupplierName, IDL.Text], [], []),
  'addExpenseRecord' : IDL.Func([IDL.Float64, Category, Description], [], []),
  'addIncomeRecord' : IDL.Func([IDL.Float64, Category, Description], [], []),
  'addPurchaseRecord' : IDL.Func(
      [ItemName, IDL.Nat, IDL.Float64, IDL.Opt(SupplierName)],
      [],
      [],
    ),
  'addSalesTransaction' : IDL.Func(
      [ItemName, IDL.Nat, IDL.Float64, IDL.Opt(CustomerName)],
      [],
      [],
    ),
  'addSupplierLoan' : IDL.Func([IDL.Float64, SupplierName, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDailyRecord' : IDL.Func([], [], []),
  'deletePurchaseRecord' : IDL.Func([], [], []),
  'deleteTransaction' : IDL.Func([], [], []),
  'getAdvancePayments' : IDL.Func([], [IDL.Vec(AdvancePayment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyRecords' : IDL.Func([IDL.Text], [IDL.Vec(DailyRecord)], ['query']),
  'getPurchaseRecords' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
  'getSalesTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getSupplierLoans' : IDL.Func([], [IDL.Vec(SupplierLoan)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'repaySupplierLoan' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'settleAdvancePayment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SupplierName = IDL.Text;
  const Category = IDL.Text;
  const Description = IDL.Text;
  const ItemName = IDL.Text;
  const CustomerName = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AdvancePayment = IDL.Record({
    'settled' : IDL.Bool,
    'supplierName' : SupplierName,
    'date' : Time,
    'amount' : IDL.Float64,
    'purpose' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DailyRecord = IDL.Record({
    'date' : Time,
    'description' : Description,
    'category' : Category,
    'amount' : IDL.Float64,
  });
  const Purchase = IDL.Record({
    'supplierName' : IDL.Opt(SupplierName),
    'date' : Time,
    'totalCost' : IDL.Float64,
    'itemName' : ItemName,
    'quantity' : IDL.Nat,
    'unitCost' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'customerName' : IDL.Opt(CustomerName),
    'date' : Time,
    'totalAmount' : IDL.Float64,
    'itemName' : ItemName,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
  });
  const SupplierLoan = IDL.Record({
    'repaid' : IDL.Bool,
    'supplierName' : SupplierName,
    'date' : Time,
    'amount' : IDL.Float64,
    'purpose' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdvancePayment' : IDL.Func(
        [IDL.Float64, SupplierName, IDL.Text],
        [],
        [],
      ),
    'addExpenseRecord' : IDL.Func([IDL.Float64, Category, Description], [], []),
    'addIncomeRecord' : IDL.Func([IDL.Float64, Category, Description], [], []),
    'addPurchaseRecord' : IDL.Func(
        [ItemName, IDL.Nat, IDL.Float64, IDL.Opt(SupplierName)],
        [],
        [],
      ),
    'addSalesTransaction' : IDL.Func(
        [ItemName, IDL.Nat, IDL.Float64, IDL.Opt(CustomerName)],
        [],
        [],
      ),
    'addSupplierLoan' : IDL.Func([IDL.Float64, SupplierName, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDailyRecord' : IDL.Func([], [], []),
    'deletePurchaseRecord' : IDL.Func([], [], []),
    'deleteTransaction' : IDL.Func([], [], []),
    'getAdvancePayments' : IDL.Func([], [IDL.Vec(AdvancePayment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyRecords' : IDL.Func([IDL.Text], [IDL.Vec(DailyRecord)], ['query']),
    'getPurchaseRecords' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
    'getSalesTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getSupplierLoans' : IDL.Func([], [IDL.Vec(SupplierLoan)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'repaySupplierLoan' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'settleAdvancePayment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };