/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdvancePayment {
  'settled' : boolean,
  'supplierName' : SupplierName,
  'date' : Time,
  'amount' : number,
  'purpose' : string,
}
export type Category = string;
export type CustomerName = string;
export interface DailyRecord {
  'date' : Time,
  'description' : Description,
  'category' : Category,
  'amount' : number,
}
export type Description = string;
export type ItemName = string;
export interface Purchase {
  'supplierName' : [] | [SupplierName],
  'date' : Time,
  'totalCost' : number,
  'itemName' : ItemName,
  'quantity' : bigint,
  'unitCost' : number,
}
export interface SupplierLoan {
  'repaid' : boolean,
  'supplierName' : SupplierName,
  'date' : Time,
  'amount' : number,
  'purpose' : string,
}
export type SupplierName = string;
export type Time = bigint;
export interface Transaction {
  'customerName' : [] | [CustomerName],
  'date' : Time,
  'totalAmount' : number,
  'itemName' : ItemName,
  'quantity' : bigint,
  'unitPrice' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdvancePayment' : ActorMethod<[number, SupplierName, string], undefined>,
  'addExpenseRecord' : ActorMethod<[number, Category, Description], undefined>,
  'addIncomeRecord' : ActorMethod<[number, Category, Description], undefined>,
  'addPurchaseRecord' : ActorMethod<
    [ItemName, bigint, number, [] | [SupplierName]],
    undefined
  >,
  'addSalesTransaction' : ActorMethod<
    [ItemName, bigint, number, [] | [CustomerName]],
    undefined
  >,
  'addSupplierLoan' : ActorMethod<[number, SupplierName, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDailyRecord' : ActorMethod<[], undefined>,
  'deletePurchaseRecord' : ActorMethod<[], undefined>,
  'deleteTransaction' : ActorMethod<[], undefined>,
  'getAdvancePayments' : ActorMethod<[], Array<AdvancePayment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyRecords' : ActorMethod<[string], Array<DailyRecord>>,
  'getPurchaseRecords' : ActorMethod<[], Array<Purchase>>,
  'getSalesTransactions' : ActorMethod<[], Array<Transaction>>,
  'getSupplierLoans' : ActorMethod<[], Array<SupplierLoan>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'repaySupplierLoan' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'settleAdvancePayment' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];